function multirotor = createMultirotor()
%-------parameters-----------
I = [   0.5119e-6 0 0; 
        0 0.5160e-6 0;
        0 0 0.5897e-6];
m = 0.022; 

% here we mix a X quadcopter. any other mix is possible by adding or
% removing propdrives.
%
% CW        CCW
% 1         4
%  \ front /
%    \   /
%    /   \
%  /       \
% 2         3
%CCW        CW
mixing = 'X';
propdrives=[    createPropDrive(-0.032,0.032,'CW'),...
                createPropDrive(-0.032,-0.032,'CCW'),...
                createPropDrive(0.032,-0.032,'CW'),...
                createPropDrive(0.032,0.032,'CCW')];

multirotor = struct( 'Roll',0,...
            'Pitch',0,...
            'Yaw',0,...
            'Omega',[0; 0; 0],...
            'Pos',[0; 0; 0],...
            'Vel',[0; 0; 0],...
            'Mass',m,...
            'Inertia',I,...
            'PropDrives',propdrives,...
            'Mixing', mixing);

end